spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/j-file-center?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      host: localhost
      port: 6379

file:
  save: local
  local:
    base-path: ./uploads